version: '2'
services:
  db:
    image: postgres
    container_name: arriana-postgresql
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: locations
      PGDATA: /data/postgres
    ports:
      - 5432:5432

  web:
    build: .

    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
